version: '3.8'
services:
  my-app:
    image: '891377271885.dkr.ecr.eu-west-2.amazonaws.com/k8s-ecr/my-app'
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    ports:
      - "3000:3000"